import { useMutation, useQuery } from "@tanstack/react-query";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import {
	ArrowLeft,
	BookOpen,
	Flame,
	Heart,
	Loader2,
	LogOut,
	User,
} from "lucide-react";
import { useState } from "react";
import {
	PACING_LABELS,
	PACING_OPTIONS,
	type PacingOption,
	SCENE_LENGTH_LABELS,
	SCENE_LENGTH_OPTIONS,
	type SceneLengthOption,
	SPICE_LABELS,
	type SpiceLevel,
	type UserPreferences,
} from "~/lib/types/preferences";

export const Route = createFileRoute("/story/create")({
	component: StoryCreatePage,
	validateSearch: (search: Record<string, unknown>) => {
		return {
			templateId: (search.templateId as string) || "",
		};
	},
});

interface Template {
	id: string;
	title: string;
	description: string;
	base_tropes: string[];
	estimated_scenes: number;
	cover_gradient: string;
}

function StoryCreatePage() {
	const { templateId } = Route.useSearch();
	const navigate = useNavigate();
	const [spiceLevel, setSpiceLevel] = useState<SpiceLevel | null>(null);
	const [pacing, setPacing] = useState<PacingOption | null>(null);
	const [sceneLength, setSceneLength] = useState<SceneLengthOption | null>(
		null,
	);
	const [storyTitle, setStoryTitle] = useState("");
	const [isCreating, setIsCreating] = useState(false);

	const handleLogout = async () => {
		try {
			await fetch("/api/auth/logout", {
				method: "POST",
				credentials: "include",
			});
			window.location.href = "/";
		} catch (error) {
			console.error("Logout error:", error);
		}
	};

	// Fetch template details
	const { data: templateData, isLoading: isLoadingTemplate } = useQuery({
		queryKey: ["template", templateId],
		queryFn: async () => {
			const response = await fetch(`/api/templates/${templateId}`, {
				credentials: "include",
			});
			if (!response.ok) throw new Error("Failed to fetch template");
			return response.json() as Promise<{ template: Template }>;
		},
		enabled: !!templateId,
	});

	// Fetch user preferences
	const { data: prefsData, isLoading: isLoadingPrefs } = useQuery({
		queryKey: ["preferences"],
		queryFn: async () => {
			const response = await fetch("/api/preferences", {
				credentials: "include",
			});
			if (!response.ok) throw new Error("Failed to fetch preferences");
			return response.json() as Promise<{ preferences: UserPreferences }>;
		},
	});

	// Fetch existing stories for this template
	const { data: existingStoriesData } = useQuery({
		queryKey: ["existing-stories", templateId],
		queryFn: async () => {
			const response = await fetch("/api/stories/user?status=in-progress", {
				credentials: "include",
			});
			if (!response.ok) throw new Error("Failed to fetch stories");
			const data = (await response.json()) as Promise<{
				stories: Array<{ template_id: string; story_title: string }>;
			}>;
			return data;
		},
		enabled: !!templateId,
	});

	const template = templateData?.template;
	const userPreferences = prefsData?.preferences;

	// Count existing stories for this template
	const existingStories =
		existingStoriesData?.stories?.filter((s) => s.template_id === templateId) ||
		[];
	const existingCount = existingStories.length;

	// Auto-generate title preview
	const autoGeneratedTitle =
		template && existingCount === 0
			? template.title
			: template
				? `${template.title} #${existingCount + 1}`
				: "";

	// Initialize overrides with user's preferences
	if (
		userPreferences &&
		spiceLevel === null &&
		pacing === null &&
		sceneLength === null
	) {
		setSpiceLevel(userPreferences.spiceLevel);
		setPacing(userPreferences.pacing);
		setSceneLength(userPreferences.sceneLength || "medium");
	}

	// Create story mutation
	const createStory = useMutation({
		mutationFn: async () => {
			const response = await fetch("/api/stories", {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				credentials: "include",
				body: JSON.stringify({
					templateId,
					storyTitle: storyTitle.trim() || undefined,
					preferences: {
						...userPreferences,
						spiceLevel: spiceLevel || userPreferences?.spiceLevel,
						pacing: pacing || userPreferences?.pacing,
						sceneLength:
							sceneLength || userPreferences?.sceneLength || "medium",
					},
				}),
			});
			if (!response.ok) {
				const error = await response.json();
				throw new Error(error.error || "Failed to create story");
			}
			return response.json() as Promise<{ story: { id: string } }>;
		},
		onSuccess: (data) => {
			// TODO: Create reading interface and navigate to /story/$id
			// For now, redirect to library
			navigate({ to: "/library" });
		},
	});

	const handleCreateStory = async () => {
		setIsCreating(true);
		try {
			await createStory.mutateAsync();
		} catch (error) {
			console.error("Failed to create story:", error);
			setIsCreating(false);
		}
	};

	const isLoading = isLoadingTemplate || isLoadingPrefs;

	return (
		<div className="min-h-screen bg-gradient-to-br from-romance-50 via-white to-romance-100">
			{/* Header */}
			<header className="bg-white shadow-sm">
				<div className="container mx-auto px-4 py-4 flex items-center justify-between">
					<div className="flex items-center gap-2">
						<Heart className="w-8 h-8 text-romance-600" fill="currentColor" />
						<span className="text-xl font-bold text-slate-900">
							Spicy Tales
						</span>
					</div>
					<nav className="flex items-center gap-4">
						<Link
							to="/browse"
							className="text-slate-700 hover:text-romance-600 font-medium"
						>
							Browse
						</Link>
						<Link
							to="/library"
							className="text-slate-700 hover:text-romance-600 font-medium"
						>
							My Library
						</Link>
						<Link
							to="/profile"
							className="flex items-center gap-2 text-slate-700 hover:text-romance-600 font-medium"
						>
							<User className="w-4 h-4" />
							Profile
						</Link>
						<button
							onClick={handleLogout}
							className="flex items-center gap-2 px-4 py-2 text-slate-700 hover:text-romance-600 font-medium"
						>
							<LogOut className="w-4 h-4" />
							Logout
						</button>
					</nav>
				</div>
			</header>

			{/* Main Content */}
			<div className="container mx-auto px-4 py-12">
				<div className="max-w-3xl mx-auto">
					{/* Back Button */}
					<button
						onClick={() => navigate({ to: "/browse" })}
						className="flex items-center gap-2 text-slate-600 hover:text-slate-900 mb-6 font-medium"
					>
						<ArrowLeft className="w-5 h-5" />
						Back to Browse
					</button>

					{/* Loading State */}
					{isLoading && (
						<div className="flex justify-center items-center py-20">
							<Loader2 className="w-8 h-8 text-romance-600 animate-spin" />
						</div>
					)}

					{/* Story Creation Form */}
					{!isLoading && template && userPreferences && (
						<div className="bg-white rounded-2xl shadow-xl p-8">
							<div className="text-center mb-8">
								<BookOpen className="w-16 h-16 text-romance-500 mx-auto mb-4" />
								<h1 className="text-3xl font-bold text-slate-900 mb-4">
									Start Your Story
								</h1>
								<p className="text-lg text-slate-600 mb-2">
									<span className="font-semibold">{template.title}</span>
								</p>
								<p className="text-sm text-slate-500">
									{template.estimated_scenes} scenes
								</p>
							</div>

							{/* Preference Customization */}
							<div className="space-y-6 mb-8">
								<div className="border-t border-slate-200 pt-6">
									<h2 className="text-xl font-bold text-slate-900 mb-2">
										Customize This Story
									</h2>
									<p className="text-slate-600 text-sm mb-6">
										Adjust these settings for this story only, or keep your
										defaults.
									</p>

									{/* Duplicate Warning */}
									{existingCount > 0 && (
										<div className="mb-6 p-4 bg-amber-50 border border-amber-200 rounded-lg">
											<div className="flex items-start gap-3">
												<BookOpen className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
												<div>
													<p className="text-amber-900 font-medium mb-1">
														You already have {existingCount} story
														{existingCount > 1 ? "s" : ""} from this template
													</p>
													<p className="text-amber-700 text-sm">
														Your new story will be named "{autoGeneratedTitle}"
														{storyTitle &&
															` (or "${storyTitle}" if you customize it)`}
													</p>
												</div>
											</div>
										</div>
									)}

									{/* Story Title */}
									<div className="mb-6">
										<label className="block text-sm font-semibold text-slate-700 mb-2">
											Story Title (Optional)
										</label>
										<input
											type="text"
											value={storyTitle}
											onChange={(e) => setStoryTitle(e.target.value)}
											placeholder={autoGeneratedTitle}
											maxLength={255}
											className="w-full px-4 py-3 rounded-lg border-2 border-slate-200 focus:border-romance-600 focus:outline-none transition-colors"
										/>
										<p className="text-xs text-slate-500 mt-2">
											{storyTitle.trim()
												? `Your story will be named: "${storyTitle}"`
												: `Default: "${autoGeneratedTitle}"`}
										</p>
									</div>

									{/* Spice Level */}
									<div className="mb-6">
										<label className="block text-sm font-semibold text-slate-700 mb-3">
											Spice Level
										</label>
										<div className="grid grid-cols-5 gap-2">
											{([1, 2, 3, 4, 5] as SpiceLevel[]).map((level) => (
												<button
													key={level}
													type="button"
													onClick={() => setSpiceLevel(level)}
													className={`p-3 rounded-lg border-2 transition-all ${
														spiceLevel === level
															? "border-romance-600 bg-romance-50"
															: "border-slate-200 bg-white hover:border-slate-300"
													}`}
												>
													<div className="flex flex-col items-center gap-1">
														<div className="flex gap-0.5">
															{Array.from({ length: level }).map((_, i) => (
																<Flame
																	key={i}
																	className="w-4 h-4 text-romance-500 fill-romance-500"
																/>
															))}
														</div>
														<span className="text-xs font-medium text-slate-700">
															{SPICE_LABELS[level].label}
														</span>
													</div>
												</button>
											))}
										</div>
										<p className="text-xs text-slate-500 mt-2">
											{spiceLevel && SPICE_LABELS[spiceLevel].description}
										</p>
									</div>

									{/* Pacing */}
									<div className="mb-6">
										<label className="block text-sm font-semibold text-slate-700 mb-3">
											Pacing
										</label>
										<div className="grid grid-cols-2 gap-3">
											{PACING_OPTIONS.map((option) => (
												<button
													key={option}
													type="button"
													onClick={() => setPacing(option)}
													className={`p-4 rounded-lg border-2 transition-all text-left ${
														pacing === option
															? "border-romance-600 bg-romance-50"
															: "border-slate-200 bg-white hover:border-slate-300"
													}`}
												>
													<div className="font-semibold text-slate-900 mb-1">
														{PACING_LABELS[option].label}
													</div>
													<div className="text-sm text-slate-600">
														{PACING_LABELS[option].description}
													</div>
												</button>
											))}
										</div>
									</div>

									{/* Scene Length */}
									<div className="mb-6">
										<label className="block text-sm font-semibold text-slate-700 mb-3">
											Scene Length
										</label>
										<div className="grid grid-cols-3 gap-3">
											{SCENE_LENGTH_OPTIONS.map((option) => (
												<button
													key={option}
													type="button"
													onClick={() => setSceneLength(option)}
													className={`p-4 rounded-lg border-2 transition-all text-center ${
														sceneLength === option
															? "border-romance-600 bg-romance-50"
															: "border-slate-200 bg-white hover:border-slate-300"
													}`}
												>
													<div className="font-semibold text-slate-900 mb-1">
														{SCENE_LENGTH_LABELS[option].label}
													</div>
													<div className="text-xs text-slate-600 mb-1">
														{SCENE_LENGTH_LABELS[option].description}
													</div>
													<div className="text-xs text-slate-500">
														{SCENE_LENGTH_LABELS[option].wordCount}
													</div>
												</button>
											))}
										</div>
									</div>
								</div>
							</div>

							{/* Error Display */}
							{createStory.error && (
								<div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg">
									<p className="text-red-800 text-sm">
										{createStory.error instanceof Error
											? createStory.error.message
											: "Failed to create story"}
									</p>
								</div>
							)}

							{/* Action Buttons */}
							<div className="flex gap-4">
								<Link
									to="/browse"
									className="flex-1 px-6 py-3 bg-slate-100 text-slate-700 rounded-lg font-medium hover:bg-slate-200 transition-colors text-center"
								>
									Cancel
								</Link>
								<button
									onClick={handleCreateStory}
									disabled={
										isCreating || !spiceLevel || !pacing || !sceneLength
									}
									className="flex-1 px-6 py-3 bg-romance-600 text-white rounded-lg font-medium hover:bg-romance-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
								>
									{isCreating ? (
										<>
											<Loader2 className="w-5 h-5 animate-spin" />
											Creating...
										</>
									) : (
										<>
											<Heart className="w-5 h-5" fill="currentColor" />
											Start Reading
										</>
									)}
								</button>
							</div>
						</div>
					)}

					{/* No Template Selected */}
					{!isLoading && !templateId && (
						<div className="bg-white rounded-2xl shadow-xl p-8 text-center">
							<h2 className="text-2xl font-bold text-slate-900 mb-4">
								No Template Selected
							</h2>
							<p className="text-slate-600 mb-6">
								Please select a template from the browse page to create your
								story.
							</p>
							<Link
								to="/browse"
								className="inline-block px-6 py-3 bg-romance-600 text-white rounded-lg font-medium hover:bg-romance-700"
							>
								Browse Templates
							</Link>
						</div>
					)}
				</div>
			</div>
		</div>
	);
}
