import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, BookOpen, Heart } from "lucide-react";
import { useState } from "react";
import { Button } from "~/components/Button";
import { EmptyState } from "~/components/EmptyState";
import { ErrorMessage } from "~/components/ErrorMessage";
import { FormInput } from "~/components/FormInput";
import { Header } from "~/components/Header";
import { LoadingSpinner } from "~/components/LoadingSpinner";
import { PageContainer } from "~/components/PageContainer";
import { RadioButtonGroup } from "~/components/RadioButtonGroup";
import { SpiceLevelSelector } from "~/components/SpiceLevelSelector";
import { useCurrentUserQuery } from "~/hooks/useCurrentUserQuery";
import { useUserPreferencesQuery } from "~/hooks/useUserPreferencesQuery";
import { useTemplateQuery } from "~/hooks/useTemplateQuery";
import { useExistingStoriesQuery } from "~/hooks/useExistingStoriesQuery";
import { useCreateStoryMutation } from "~/hooks/useCreateStoryMutation";
import {
	PACING_LABELS,
	PACING_OPTIONS,
	type PacingOption,
	SCENE_LENGTH_LABELS,
	SCENE_LENGTH_OPTIONS,
	type SceneLengthOption,
	type SpiceLevel,
} from "~/lib/types/preferences";
import type { Template } from "~/lib/api/types";

export const Route = createFileRoute("/story/create")({
	component: StoryCreatePage,
	validateSearch: (search: Record<string, unknown>) => {
		return {
			templateId: (search.templateId as string) || "",
		};
	},
});

function StoryCreatePage() {
	const { templateId } = Route.useSearch();
	const navigate = useNavigate();
	const [spiceLevel, setSpiceLevel] = useState<SpiceLevel | null>(null);
	const [pacing, setPacing] = useState<PacingOption | null>(null);
	const [sceneLength, setSceneLength] = useState<SceneLengthOption | null>(
		null,
	);
	const [storyTitle, setStoryTitle] = useState("");
	const [isCreating, setIsCreating] = useState(false);

	// Fetch current user profile
	const { data: profileData } = useCurrentUserQuery();

	// Fetch template details
	const { data: templateData, isLoading: isLoadingTemplate } = useTemplateQuery(templateId, !!templateId);

	// Fetch user preferences
	const { data: prefsData, isLoading: isLoadingPrefs } = useUserPreferencesQuery();

	// Fetch existing stories for this template
	const { data: existingStoriesData } = useExistingStoriesQuery(!!templateId);

	const template = templateData?.template;
	const userPreferences = prefsData?.preferences;

	// Count existing stories for this template
	const existingStories =
		existingStoriesData?.stories?.filter((s) => s.template_id === templateId) ||
		[];
	const existingCount = existingStories.length;

	// Auto-generate title preview
	const autoGeneratedTitle =
		template && existingCount === 0
			? template.title
			: template
				? `${template.title} #${existingCount + 1}`
				: "";

	// Initialize overrides with user's preferences
	if (
		userPreferences &&
		spiceLevel === null &&
		pacing === null &&
		sceneLength === null
	) {
		setSpiceLevel(userPreferences.spiceLevel);
		setPacing(userPreferences.pacing);
		setSceneLength(userPreferences.sceneLength || "medium");
	}

	// Create story mutation
	const createStory = useCreateStoryMutation();

	const handleCreateStory = async () => {
		setIsCreating(true);
		try {
			const result = await createStory.mutateAsync({
				templateId,
				storyTitle: storyTitle.trim() || undefined,
				preferences: {
					...userPreferences!,
					spiceLevel: spiceLevel || userPreferences?.spiceLevel!,
					pacing: pacing || userPreferences?.pacing!,
					sceneLength:
						sceneLength || userPreferences?.sceneLength || "medium",
				},
			});
			// Navigate to library after successful creation
			navigate({ to: "/library" });
		} catch (error) {
			console.error("Failed to create story:", error);
			setIsCreating(false);
		}
	};

	const isLoading = isLoadingTemplate || isLoadingPrefs;

	return (
		<div className="min-h-screen bg-linear-to-br from-romance-50 via-white to-romance-100">
			<Header currentPath="" userRole={profileData?.role} />

			<PageContainer maxWidth="md">
				{/* Back Button */}
				<button
					onClick={() => navigate({ to: "/browse" })}
					className="flex items-center gap-2 text-slate-600 hover:text-slate-900 mb-6 font-medium"
				>
					<ArrowLeft className="w-5 h-5" />
					Back to Browse
				</button>

				{/* Loading State */}
				{isLoading && <LoadingSpinner message="Loading your story..." />}

				{/* Story Creation Form */}
				{!isLoading && template && userPreferences && (
					<div className="bg-white rounded-2xl shadow-xl p-8">
						<div className="text-center mb-8">
							<BookOpen className="w-16 h-16 text-romance-500 mx-auto mb-4" />
							<h1 className="text-3xl font-bold text-slate-900 mb-4">
								Start Your Story
							</h1>
							<p className="text-lg text-slate-600 mb-2">
								<span className="font-semibold">{template.title}</span>
							</p>
							<p className="text-sm text-slate-500">
								{template.estimated_scenes} scenes
							</p>
						</div>

						{/* Preference Customization */}
						<div className="space-y-6 mb-8">
							<div className="border-t border-slate-200 pt-6">
								<h2 className="text-xl font-bold text-slate-900 mb-2">
									Customize This Story
								</h2>
								<p className="text-slate-600 text-sm mb-6">
									Adjust these settings for this story only, or keep your
									defaults.
								</p>

								{/* Duplicate Warning */}
								{existingCount > 0 && (
									<div className="mb-6 p-4 bg-amber-50 border border-amber-200 rounded-lg">
										<div className="flex items-start gap-3">
											<BookOpen className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
											<div>
												<p className="text-amber-900 font-medium mb-1">
													You already have {existingCount} story
													{existingCount > 1 ? "s" : ""} from this template
												</p>
												<p className="text-amber-700 text-sm">
													Your new story will be named "{autoGeneratedTitle}"
													{storyTitle &&
														` (or "${storyTitle}" if you customize it)`}
												</p>
											</div>
										</div>
									</div>
								)}

						{/* Story Title */}
						<div className="mb-6">
							<FormInput
								label="Story Title (Optional)"
								type="text"
								value={storyTitle}
								onChange={(e) => setStoryTitle(e.target.value)}
								placeholder={autoGeneratedTitle}
								maxLength={255}
								helperText={
									storyTitle.trim()
										? `Your story will be named: "${storyTitle}"`
										: `Default: "${autoGeneratedTitle}"`
								}
							/>
						</div>								{/* Spice Level */}
								<SpiceLevelSelector
									value={spiceLevel}
									onChange={setSpiceLevel}
								/>

								{/* Pacing */}
								<div className="mb-6">
									<RadioButtonGroup
										label="Pacing"
										value={pacing}
										options={PACING_OPTIONS.map((option) => ({
											value: option,
											label: PACING_LABELS[option].label,
											description: PACING_LABELS[option].description,
										}))}
										onChange={setPacing}
										columns={2}
									/>
								</div>

								{/* Scene Length */}
								<div className="mb-6">
									<RadioButtonGroup
										label="Scene Length"
										value={sceneLength}
										options={SCENE_LENGTH_OPTIONS.map((option) => ({
											value: option,
											label: SCENE_LENGTH_LABELS[option].label,
											description: `${SCENE_LENGTH_LABELS[option].description} (${SCENE_LENGTH_LABELS[option].wordCount})`,
										}))}
										onChange={setSceneLength}
										columns={3}
									/>
								</div>
							</div>
						</div>

						{/* Error Display */}
						{createStory.error && (
							<ErrorMessage
								message={
									createStory.error instanceof Error
										? createStory.error.message
										: "Failed to create story"
								}
								className="mb-6"
							/>
						)}

						{/* Action Buttons */}
						<div className="flex gap-4">
							<Button
								variant="secondary"
								className="flex-1"
								onClick={() => navigate({ to: "/browse" })}
							>
								Cancel
							</Button>
							<Button
								onClick={handleCreateStory}
								disabled={!spiceLevel || !pacing || !sceneLength}
								loading={isCreating}
								className="flex-1"
							>
								<Heart className="w-5 h-5" fill="currentColor" />
								Start Reading
							</Button>
						</div>
					</div>
				)}

				{/* No Template Selected */}
				{!isLoading && !templateId && (
					<EmptyState
						icon={BookOpen}
						title="No Template Selected"
						description="Please select a template from the browse page to create your story."
						action={{ label: "Browse Templates", href: "/browse" }}
					/>
				)}
			</PageContainer>
		</div>
	);
}
