/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplateIdRouteImport } from './routes/template/$id'
import { Route as StoryCreateRouteImport } from './routes/story/create'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthOnboardingRouteImport } from './routes/auth/onboarding'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiPreferencesRouteImport } from './routes/api/preferences'
import { Route as ApiTemplatesIndexRouteImport } from './routes/api/templates/index'
import { Route as ApiStoriesIndexRouteImport } from './routes/api/stories/index'
import { Route as ApiProfileIndexRouteImport } from './routes/api/profile/index'
import { Route as StoryIdReadRouteImport } from './routes/story/$id.read'
import { Route as ApiTemplatesIdRouteImport } from './routes/api/templates/$id'
import { Route as ApiStoriesUserRouteImport } from './routes/api/stories/user'
import { Route as ApiStoriesIdRouteImport } from './routes/api/stories/$id'
import { Route as ApiProfilePasswordRouteImport } from './routes/api/profile/password'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiAdminDashboardRouteImport } from './routes/api/admin/dashboard'
import { Route as ApiAdminAuditLogsRouteImport } from './routes/api/admin/audit-logs'
import { Route as ApiAdminUsersIndexRouteImport } from './routes/api/admin/users/index'
import { Route as ApiAdminTemplatesIndexRouteImport } from './routes/api/admin/templates/index'
import { Route as ApiStoriesIdSceneRouteImport } from './routes/api/stories/$id.scene'
import { Route as ApiStoriesIdChooseRouteImport } from './routes/api/stories/$id.choose'
import { Route as ApiAuthCallbackGoogleRouteImport } from './routes/api/auth/callback.google'
import { Route as ApiAdminUsersIdRouteImport } from './routes/api/admin/users/$id'
import { Route as ApiAdminTemplatesIdRouteImport } from './routes/api/admin/templates/$id'
import { Route as ApiAdminTemplatesIdStatusRouteImport } from './routes/api/admin/templates/$id.status'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateIdRoute = TemplateIdRouteImport.update({
  id: '/template/$id',
  path: '/template/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryCreateRoute = StoryCreateRouteImport.update({
  id: '/story/create',
  path: '/story/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/auth/onboarding',
  path: '/auth/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreferencesRoute = ApiPreferencesRouteImport.update({
  id: '/api/preferences',
  path: '/api/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesIndexRoute = ApiTemplatesIndexRouteImport.update({
  id: '/api/templates/',
  path: '/api/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesIndexRoute = ApiStoriesIndexRouteImport.update({
  id: '/api/stories/',
  path: '/api/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileIndexRoute = ApiProfileIndexRouteImport.update({
  id: '/api/profile/',
  path: '/api/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIdReadRoute = StoryIdReadRouteImport.update({
  id: '/story/$id/read',
  path: '/story/$id/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesIdRoute = ApiTemplatesIdRouteImport.update({
  id: '/api/templates/$id',
  path: '/api/templates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesUserRoute = ApiStoriesUserRouteImport.update({
  id: '/api/stories/user',
  path: '/api/stories/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesIdRoute = ApiStoriesIdRouteImport.update({
  id: '/api/stories/$id',
  path: '/api/stories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilePasswordRoute = ApiProfilePasswordRouteImport.update({
  id: '/api/profile/password',
  path: '/api/profile/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDashboardRoute = ApiAdminDashboardRouteImport.update({
  id: '/api/admin/dashboard',
  path: '/api/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuditLogsRoute = ApiAdminAuditLogsRouteImport.update({
  id: '/api/admin/audit-logs',
  path: '/api/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersIndexRoute = ApiAdminUsersIndexRouteImport.update({
  id: '/api/admin/users/',
  path: '/api/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTemplatesIndexRoute = ApiAdminTemplatesIndexRouteImport.update({
  id: '/api/admin/templates/',
  path: '/api/admin/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesIdSceneRoute = ApiStoriesIdSceneRouteImport.update({
  id: '/scene',
  path: '/scene',
  getParentRoute: () => ApiStoriesIdRoute,
} as any)
const ApiStoriesIdChooseRoute = ApiStoriesIdChooseRouteImport.update({
  id: '/choose',
  path: '/choose',
  getParentRoute: () => ApiStoriesIdRoute,
} as any)
const ApiAuthCallbackGoogleRoute = ApiAuthCallbackGoogleRouteImport.update({
  id: '/api/auth/callback/google',
  path: '/api/auth/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersIdRoute = ApiAdminUsersIdRouteImport.update({
  id: '/api/admin/users/$id',
  path: '/api/admin/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTemplatesIdRoute = ApiAdminTemplatesIdRouteImport.update({
  id: '/api/admin/templates/$id',
  path: '/api/admin/templates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTemplatesIdStatusRoute =
  ApiAdminTemplatesIdStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => ApiAdminTemplatesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/library': typeof LibraryRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/api/preferences': typeof ApiPreferencesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/signup': typeof AuthSignupRoute
  '/story/create': typeof StoryCreateRoute
  '/template/$id': typeof TemplateIdRoute
  '/api/admin/audit-logs': typeof ApiAdminAuditLogsRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/profile/password': typeof ApiProfilePasswordRoute
  '/api/stories/$id': typeof ApiStoriesIdRouteWithChildren
  '/api/stories/user': typeof ApiStoriesUserRoute
  '/api/templates/$id': typeof ApiTemplatesIdRoute
  '/story/$id/read': typeof StoryIdReadRoute
  '/api/profile': typeof ApiProfileIndexRoute
  '/api/stories': typeof ApiStoriesIndexRoute
  '/api/templates': typeof ApiTemplatesIndexRoute
  '/api/admin/templates/$id': typeof ApiAdminTemplatesIdRouteWithChildren
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/stories/$id/choose': typeof ApiStoriesIdChooseRoute
  '/api/stories/$id/scene': typeof ApiStoriesIdSceneRoute
  '/api/admin/templates': typeof ApiAdminTemplatesIndexRoute
  '/api/admin/users': typeof ApiAdminUsersIndexRoute
  '/api/admin/templates/$id/status': typeof ApiAdminTemplatesIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/library': typeof LibraryRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/api/preferences': typeof ApiPreferencesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/signup': typeof AuthSignupRoute
  '/story/create': typeof StoryCreateRoute
  '/template/$id': typeof TemplateIdRoute
  '/api/admin/audit-logs': typeof ApiAdminAuditLogsRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/profile/password': typeof ApiProfilePasswordRoute
  '/api/stories/$id': typeof ApiStoriesIdRouteWithChildren
  '/api/stories/user': typeof ApiStoriesUserRoute
  '/api/templates/$id': typeof ApiTemplatesIdRoute
  '/story/$id/read': typeof StoryIdReadRoute
  '/api/profile': typeof ApiProfileIndexRoute
  '/api/stories': typeof ApiStoriesIndexRoute
  '/api/templates': typeof ApiTemplatesIndexRoute
  '/api/admin/templates/$id': typeof ApiAdminTemplatesIdRouteWithChildren
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/stories/$id/choose': typeof ApiStoriesIdChooseRoute
  '/api/stories/$id/scene': typeof ApiStoriesIdSceneRoute
  '/api/admin/templates': typeof ApiAdminTemplatesIndexRoute
  '/api/admin/users': typeof ApiAdminUsersIndexRoute
  '/api/admin/templates/$id/status': typeof ApiAdminTemplatesIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/library': typeof LibraryRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/api/preferences': typeof ApiPreferencesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/signup': typeof AuthSignupRoute
  '/story/create': typeof StoryCreateRoute
  '/template/$id': typeof TemplateIdRoute
  '/api/admin/audit-logs': typeof ApiAdminAuditLogsRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/profile/password': typeof ApiProfilePasswordRoute
  '/api/stories/$id': typeof ApiStoriesIdRouteWithChildren
  '/api/stories/user': typeof ApiStoriesUserRoute
  '/api/templates/$id': typeof ApiTemplatesIdRoute
  '/story/$id/read': typeof StoryIdReadRoute
  '/api/profile/': typeof ApiProfileIndexRoute
  '/api/stories/': typeof ApiStoriesIndexRoute
  '/api/templates/': typeof ApiTemplatesIndexRoute
  '/api/admin/templates/$id': typeof ApiAdminTemplatesIdRouteWithChildren
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/stories/$id/choose': typeof ApiStoriesIdChooseRoute
  '/api/stories/$id/scene': typeof ApiStoriesIdSceneRoute
  '/api/admin/templates/': typeof ApiAdminTemplatesIndexRoute
  '/api/admin/users/': typeof ApiAdminUsersIndexRoute
  '/api/admin/templates/$id/status': typeof ApiAdminTemplatesIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/library'
    | '/preferences'
    | '/profile'
    | '/api/preferences'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/signup'
    | '/story/create'
    | '/template/$id'
    | '/api/admin/audit-logs'
    | '/api/admin/dashboard'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/signup'
    | '/api/profile/password'
    | '/api/stories/$id'
    | '/api/stories/user'
    | '/api/templates/$id'
    | '/story/$id/read'
    | '/api/profile'
    | '/api/stories'
    | '/api/templates'
    | '/api/admin/templates/$id'
    | '/api/admin/users/$id'
    | '/api/auth/callback/google'
    | '/api/stories/$id/choose'
    | '/api/stories/$id/scene'
    | '/api/admin/templates'
    | '/api/admin/users'
    | '/api/admin/templates/$id/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/library'
    | '/preferences'
    | '/profile'
    | '/api/preferences'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/signup'
    | '/story/create'
    | '/template/$id'
    | '/api/admin/audit-logs'
    | '/api/admin/dashboard'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/signup'
    | '/api/profile/password'
    | '/api/stories/$id'
    | '/api/stories/user'
    | '/api/templates/$id'
    | '/story/$id/read'
    | '/api/profile'
    | '/api/stories'
    | '/api/templates'
    | '/api/admin/templates/$id'
    | '/api/admin/users/$id'
    | '/api/auth/callback/google'
    | '/api/stories/$id/choose'
    | '/api/stories/$id/scene'
    | '/api/admin/templates'
    | '/api/admin/users'
    | '/api/admin/templates/$id/status'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/library'
    | '/preferences'
    | '/profile'
    | '/api/preferences'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/signup'
    | '/story/create'
    | '/template/$id'
    | '/api/admin/audit-logs'
    | '/api/admin/dashboard'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/signup'
    | '/api/profile/password'
    | '/api/stories/$id'
    | '/api/stories/user'
    | '/api/templates/$id'
    | '/story/$id/read'
    | '/api/profile/'
    | '/api/stories/'
    | '/api/templates/'
    | '/api/admin/templates/$id'
    | '/api/admin/users/$id'
    | '/api/auth/callback/google'
    | '/api/stories/$id/choose'
    | '/api/stories/$id/scene'
    | '/api/admin/templates/'
    | '/api/admin/users/'
    | '/api/admin/templates/$id/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  LibraryRoute: typeof LibraryRoute
  PreferencesRoute: typeof PreferencesRoute
  ProfileRoute: typeof ProfileRoute
  ApiPreferencesRoute: typeof ApiPreferencesRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthSignupRoute: typeof AuthSignupRoute
  StoryCreateRoute: typeof StoryCreateRoute
  TemplateIdRoute: typeof TemplateIdRoute
  ApiAdminAuditLogsRoute: typeof ApiAdminAuditLogsRoute
  ApiAdminDashboardRoute: typeof ApiAdminDashboardRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiProfilePasswordRoute: typeof ApiProfilePasswordRoute
  ApiStoriesIdRoute: typeof ApiStoriesIdRouteWithChildren
  ApiStoriesUserRoute: typeof ApiStoriesUserRoute
  ApiTemplatesIdRoute: typeof ApiTemplatesIdRoute
  StoryIdReadRoute: typeof StoryIdReadRoute
  ApiProfileIndexRoute: typeof ApiProfileIndexRoute
  ApiStoriesIndexRoute: typeof ApiStoriesIndexRoute
  ApiTemplatesIndexRoute: typeof ApiTemplatesIndexRoute
  ApiAdminTemplatesIdRoute: typeof ApiAdminTemplatesIdRouteWithChildren
  ApiAdminUsersIdRoute: typeof ApiAdminUsersIdRoute
  ApiAuthCallbackGoogleRoute: typeof ApiAuthCallbackGoogleRoute
  ApiAdminTemplatesIndexRoute: typeof ApiAdminTemplatesIndexRoute
  ApiAdminUsersIndexRoute: typeof ApiAdminUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$id': {
      id: '/template/$id'
      path: '/template/$id'
      fullPath: '/template/$id'
      preLoaderRoute: typeof TemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/create': {
      id: '/story/create'
      path: '/story/create'
      fullPath: '/story/create'
      preLoaderRoute: typeof StoryCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/onboarding': {
      id: '/auth/onboarding'
      path: '/auth/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preferences': {
      id: '/api/preferences'
      path: '/api/preferences'
      fullPath: '/api/preferences'
      preLoaderRoute: typeof ApiPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates/': {
      id: '/api/templates/'
      path: '/api/templates'
      fullPath: '/api/templates'
      preLoaderRoute: typeof ApiTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories/': {
      id: '/api/stories/'
      path: '/api/stories'
      fullPath: '/api/stories'
      preLoaderRoute: typeof ApiStoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/': {
      id: '/api/profile/'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$id/read': {
      id: '/story/$id/read'
      path: '/story/$id/read'
      fullPath: '/story/$id/read'
      preLoaderRoute: typeof StoryIdReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates/$id': {
      id: '/api/templates/$id'
      path: '/api/templates/$id'
      fullPath: '/api/templates/$id'
      preLoaderRoute: typeof ApiTemplatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories/user': {
      id: '/api/stories/user'
      path: '/api/stories/user'
      fullPath: '/api/stories/user'
      preLoaderRoute: typeof ApiStoriesUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories/$id': {
      id: '/api/stories/$id'
      path: '/api/stories/$id'
      fullPath: '/api/stories/$id'
      preLoaderRoute: typeof ApiStoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/password': {
      id: '/api/profile/password'
      path: '/api/profile/password'
      fullPath: '/api/profile/password'
      preLoaderRoute: typeof ApiProfilePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/dashboard': {
      id: '/api/admin/dashboard'
      path: '/api/admin/dashboard'
      fullPath: '/api/admin/dashboard'
      preLoaderRoute: typeof ApiAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/audit-logs': {
      id: '/api/admin/audit-logs'
      path: '/api/admin/audit-logs'
      fullPath: '/api/admin/audit-logs'
      preLoaderRoute: typeof ApiAdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/': {
      id: '/api/admin/users/'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/templates/': {
      id: '/api/admin/templates/'
      path: '/api/admin/templates'
      fullPath: '/api/admin/templates'
      preLoaderRoute: typeof ApiAdminTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories/$id/scene': {
      id: '/api/stories/$id/scene'
      path: '/scene'
      fullPath: '/api/stories/$id/scene'
      preLoaderRoute: typeof ApiStoriesIdSceneRouteImport
      parentRoute: typeof ApiStoriesIdRoute
    }
    '/api/stories/$id/choose': {
      id: '/api/stories/$id/choose'
      path: '/choose'
      fullPath: '/api/stories/$id/choose'
      preLoaderRoute: typeof ApiStoriesIdChooseRouteImport
      parentRoute: typeof ApiStoriesIdRoute
    }
    '/api/auth/callback/google': {
      id: '/api/auth/callback/google'
      path: '/api/auth/callback/google'
      fullPath: '/api/auth/callback/google'
      preLoaderRoute: typeof ApiAuthCallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/$id': {
      id: '/api/admin/users/$id'
      path: '/api/admin/users/$id'
      fullPath: '/api/admin/users/$id'
      preLoaderRoute: typeof ApiAdminUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/templates/$id': {
      id: '/api/admin/templates/$id'
      path: '/api/admin/templates/$id'
      fullPath: '/api/admin/templates/$id'
      preLoaderRoute: typeof ApiAdminTemplatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/templates/$id/status': {
      id: '/api/admin/templates/$id/status'
      path: '/status'
      fullPath: '/api/admin/templates/$id/status'
      preLoaderRoute: typeof ApiAdminTemplatesIdStatusRouteImport
      parentRoute: typeof ApiAdminTemplatesIdRoute
    }
  }
}

interface ApiStoriesIdRouteChildren {
  ApiStoriesIdChooseRoute: typeof ApiStoriesIdChooseRoute
  ApiStoriesIdSceneRoute: typeof ApiStoriesIdSceneRoute
}

const ApiStoriesIdRouteChildren: ApiStoriesIdRouteChildren = {
  ApiStoriesIdChooseRoute: ApiStoriesIdChooseRoute,
  ApiStoriesIdSceneRoute: ApiStoriesIdSceneRoute,
}

const ApiStoriesIdRouteWithChildren = ApiStoriesIdRoute._addFileChildren(
  ApiStoriesIdRouteChildren,
)

interface ApiAdminTemplatesIdRouteChildren {
  ApiAdminTemplatesIdStatusRoute: typeof ApiAdminTemplatesIdStatusRoute
}

const ApiAdminTemplatesIdRouteChildren: ApiAdminTemplatesIdRouteChildren = {
  ApiAdminTemplatesIdStatusRoute: ApiAdminTemplatesIdStatusRoute,
}

const ApiAdminTemplatesIdRouteWithChildren =
  ApiAdminTemplatesIdRoute._addFileChildren(ApiAdminTemplatesIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  LibraryRoute: LibraryRoute,
  PreferencesRoute: PreferencesRoute,
  ProfileRoute: ProfileRoute,
  ApiPreferencesRoute: ApiPreferencesRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthSignupRoute: AuthSignupRoute,
  StoryCreateRoute: StoryCreateRoute,
  TemplateIdRoute: TemplateIdRoute,
  ApiAdminAuditLogsRoute: ApiAdminAuditLogsRoute,
  ApiAdminDashboardRoute: ApiAdminDashboardRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiProfilePasswordRoute: ApiProfilePasswordRoute,
  ApiStoriesIdRoute: ApiStoriesIdRouteWithChildren,
  ApiStoriesUserRoute: ApiStoriesUserRoute,
  ApiTemplatesIdRoute: ApiTemplatesIdRoute,
  StoryIdReadRoute: StoryIdReadRoute,
  ApiProfileIndexRoute: ApiProfileIndexRoute,
  ApiStoriesIndexRoute: ApiStoriesIndexRoute,
  ApiTemplatesIndexRoute: ApiTemplatesIndexRoute,
  ApiAdminTemplatesIdRoute: ApiAdminTemplatesIdRouteWithChildren,
  ApiAdminUsersIdRoute: ApiAdminUsersIdRoute,
  ApiAuthCallbackGoogleRoute: ApiAuthCallbackGoogleRoute,
  ApiAdminTemplatesIndexRoute: ApiAdminTemplatesIndexRoute,
  ApiAdminUsersIndexRoute: ApiAdminUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
