/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplateIdRouteImport } from './routes/template/$id'
import { Route as StoryCreateRouteImport } from './routes/story/create'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthOnboardingRouteImport } from './routes/auth/onboarding'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiPreferencesRouteImport } from './routes/api/preferences'
import { Route as ApiTemplatesIndexRouteImport } from './routes/api/templates/index'
import { Route as ApiStoriesIndexRouteImport } from './routes/api/stories/index'
import { Route as ApiProfileIndexRouteImport } from './routes/api/profile/index'
import { Route as StoryIdReadRouteImport } from './routes/story/$id.read'
import { Route as ApiTemplatesIdRouteImport } from './routes/api/templates/$id'
import { Route as ApiStoriesUserRouteImport } from './routes/api/stories/user'
import { Route as ApiProfilePasswordRouteImport } from './routes/api/profile/password'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiStoriesIdSceneRouteImport } from './routes/api/stories/$id.scene'
import { Route as ApiStoriesIdChooseRouteImport } from './routes/api/stories/$id.choose'
import { Route as ApiAuthCallbackGoogleRouteImport } from './routes/api/auth/callback.google'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateIdRoute = TemplateIdRouteImport.update({
  id: '/template/$id',
  path: '/template/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryCreateRoute = StoryCreateRouteImport.update({
  id: '/story/create',
  path: '/story/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/auth/onboarding',
  path: '/auth/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreferencesRoute = ApiPreferencesRouteImport.update({
  id: '/api/preferences',
  path: '/api/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesIndexRoute = ApiTemplatesIndexRouteImport.update({
  id: '/api/templates/',
  path: '/api/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesIndexRoute = ApiStoriesIndexRouteImport.update({
  id: '/api/stories/',
  path: '/api/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileIndexRoute = ApiProfileIndexRouteImport.update({
  id: '/api/profile/',
  path: '/api/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIdReadRoute = StoryIdReadRouteImport.update({
  id: '/story/$id/read',
  path: '/story/$id/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesIdRoute = ApiTemplatesIdRouteImport.update({
  id: '/api/templates/$id',
  path: '/api/templates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesUserRoute = ApiStoriesUserRouteImport.update({
  id: '/api/stories/user',
  path: '/api/stories/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilePasswordRoute = ApiProfilePasswordRouteImport.update({
  id: '/api/profile/password',
  path: '/api/profile/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesIdSceneRoute = ApiStoriesIdSceneRouteImport.update({
  id: '/api/stories/$id/scene',
  path: '/api/stories/$id/scene',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesIdChooseRoute = ApiStoriesIdChooseRouteImport.update({
  id: '/api/stories/$id/choose',
  path: '/api/stories/$id/choose',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackGoogleRoute = ApiAuthCallbackGoogleRouteImport.update({
  id: '/api/auth/callback/google',
  path: '/api/auth/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/api/preferences': typeof ApiPreferencesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/signup': typeof AuthSignupRoute
  '/story/create': typeof StoryCreateRoute
  '/template/$id': typeof TemplateIdRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/profile/password': typeof ApiProfilePasswordRoute
  '/api/stories/user': typeof ApiStoriesUserRoute
  '/api/templates/$id': typeof ApiTemplatesIdRoute
  '/story/$id/read': typeof StoryIdReadRoute
  '/api/profile': typeof ApiProfileIndexRoute
  '/api/stories': typeof ApiStoriesIndexRoute
  '/api/templates': typeof ApiTemplatesIndexRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/stories/$id/choose': typeof ApiStoriesIdChooseRoute
  '/api/stories/$id/scene': typeof ApiStoriesIdSceneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/api/preferences': typeof ApiPreferencesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/signup': typeof AuthSignupRoute
  '/story/create': typeof StoryCreateRoute
  '/template/$id': typeof TemplateIdRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/profile/password': typeof ApiProfilePasswordRoute
  '/api/stories/user': typeof ApiStoriesUserRoute
  '/api/templates/$id': typeof ApiTemplatesIdRoute
  '/story/$id/read': typeof StoryIdReadRoute
  '/api/profile': typeof ApiProfileIndexRoute
  '/api/stories': typeof ApiStoriesIndexRoute
  '/api/templates': typeof ApiTemplatesIndexRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/stories/$id/choose': typeof ApiStoriesIdChooseRoute
  '/api/stories/$id/scene': typeof ApiStoriesIdSceneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/api/preferences': typeof ApiPreferencesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/signup': typeof AuthSignupRoute
  '/story/create': typeof StoryCreateRoute
  '/template/$id': typeof TemplateIdRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/profile/password': typeof ApiProfilePasswordRoute
  '/api/stories/user': typeof ApiStoriesUserRoute
  '/api/templates/$id': typeof ApiTemplatesIdRoute
  '/story/$id/read': typeof StoryIdReadRoute
  '/api/profile/': typeof ApiProfileIndexRoute
  '/api/stories/': typeof ApiStoriesIndexRoute
  '/api/templates/': typeof ApiTemplatesIndexRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/stories/$id/choose': typeof ApiStoriesIdChooseRoute
  '/api/stories/$id/scene': typeof ApiStoriesIdSceneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/library'
    | '/profile'
    | '/api/preferences'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/signup'
    | '/story/create'
    | '/template/$id'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/signup'
    | '/api/profile/password'
    | '/api/stories/user'
    | '/api/templates/$id'
    | '/story/$id/read'
    | '/api/profile'
    | '/api/stories'
    | '/api/templates'
    | '/api/auth/callback/google'
    | '/api/stories/$id/choose'
    | '/api/stories/$id/scene'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/library'
    | '/profile'
    | '/api/preferences'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/signup'
    | '/story/create'
    | '/template/$id'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/signup'
    | '/api/profile/password'
    | '/api/stories/user'
    | '/api/templates/$id'
    | '/story/$id/read'
    | '/api/profile'
    | '/api/stories'
    | '/api/templates'
    | '/api/auth/callback/google'
    | '/api/stories/$id/choose'
    | '/api/stories/$id/scene'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/library'
    | '/profile'
    | '/api/preferences'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/signup'
    | '/story/create'
    | '/template/$id'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/signup'
    | '/api/profile/password'
    | '/api/stories/user'
    | '/api/templates/$id'
    | '/story/$id/read'
    | '/api/profile/'
    | '/api/stories/'
    | '/api/templates/'
    | '/api/auth/callback/google'
    | '/api/stories/$id/choose'
    | '/api/stories/$id/scene'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  LibraryRoute: typeof LibraryRoute
  ProfileRoute: typeof ProfileRoute
  ApiPreferencesRoute: typeof ApiPreferencesRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthSignupRoute: typeof AuthSignupRoute
  StoryCreateRoute: typeof StoryCreateRoute
  TemplateIdRoute: typeof TemplateIdRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiProfilePasswordRoute: typeof ApiProfilePasswordRoute
  ApiStoriesUserRoute: typeof ApiStoriesUserRoute
  ApiTemplatesIdRoute: typeof ApiTemplatesIdRoute
  StoryIdReadRoute: typeof StoryIdReadRoute
  ApiProfileIndexRoute: typeof ApiProfileIndexRoute
  ApiStoriesIndexRoute: typeof ApiStoriesIndexRoute
  ApiTemplatesIndexRoute: typeof ApiTemplatesIndexRoute
  ApiAuthCallbackGoogleRoute: typeof ApiAuthCallbackGoogleRoute
  ApiStoriesIdChooseRoute: typeof ApiStoriesIdChooseRoute
  ApiStoriesIdSceneRoute: typeof ApiStoriesIdSceneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$id': {
      id: '/template/$id'
      path: '/template/$id'
      fullPath: '/template/$id'
      preLoaderRoute: typeof TemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/create': {
      id: '/story/create'
      path: '/story/create'
      fullPath: '/story/create'
      preLoaderRoute: typeof StoryCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/onboarding': {
      id: '/auth/onboarding'
      path: '/auth/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preferences': {
      id: '/api/preferences'
      path: '/api/preferences'
      fullPath: '/api/preferences'
      preLoaderRoute: typeof ApiPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates/': {
      id: '/api/templates/'
      path: '/api/templates'
      fullPath: '/api/templates'
      preLoaderRoute: typeof ApiTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories/': {
      id: '/api/stories/'
      path: '/api/stories'
      fullPath: '/api/stories'
      preLoaderRoute: typeof ApiStoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/': {
      id: '/api/profile/'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$id/read': {
      id: '/story/$id/read'
      path: '/story/$id/read'
      fullPath: '/story/$id/read'
      preLoaderRoute: typeof StoryIdReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates/$id': {
      id: '/api/templates/$id'
      path: '/api/templates/$id'
      fullPath: '/api/templates/$id'
      preLoaderRoute: typeof ApiTemplatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories/user': {
      id: '/api/stories/user'
      path: '/api/stories/user'
      fullPath: '/api/stories/user'
      preLoaderRoute: typeof ApiStoriesUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/password': {
      id: '/api/profile/password'
      path: '/api/profile/password'
      fullPath: '/api/profile/password'
      preLoaderRoute: typeof ApiProfilePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories/$id/scene': {
      id: '/api/stories/$id/scene'
      path: '/api/stories/$id/scene'
      fullPath: '/api/stories/$id/scene'
      preLoaderRoute: typeof ApiStoriesIdSceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories/$id/choose': {
      id: '/api/stories/$id/choose'
      path: '/api/stories/$id/choose'
      fullPath: '/api/stories/$id/choose'
      preLoaderRoute: typeof ApiStoriesIdChooseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/google': {
      id: '/api/auth/callback/google'
      path: '/api/auth/callback/google'
      fullPath: '/api/auth/callback/google'
      preLoaderRoute: typeof ApiAuthCallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  LibraryRoute: LibraryRoute,
  ProfileRoute: ProfileRoute,
  ApiPreferencesRoute: ApiPreferencesRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthSignupRoute: AuthSignupRoute,
  StoryCreateRoute: StoryCreateRoute,
  TemplateIdRoute: TemplateIdRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiProfilePasswordRoute: ApiProfilePasswordRoute,
  ApiStoriesUserRoute: ApiStoriesUserRoute,
  ApiTemplatesIdRoute: ApiTemplatesIdRoute,
  StoryIdReadRoute: StoryIdReadRoute,
  ApiProfileIndexRoute: ApiProfileIndexRoute,
  ApiStoriesIndexRoute: ApiStoriesIndexRoute,
  ApiTemplatesIndexRoute: ApiTemplatesIndexRoute,
  ApiAuthCallbackGoogleRoute: ApiAuthCallbackGoogleRoute,
  ApiStoriesIdChooseRoute: ApiStoriesIdChooseRoute,
  ApiStoriesIdSceneRoute: ApiStoriesIdSceneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
