/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TemplateIdRouteImport } from './routes/template/$id'
import { Route as StoryCreateRouteImport } from './routes/story/create'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthOnboardingRouteImport } from './routes/auth/onboarding'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiPreferencesRouteImport } from './routes/api/preferences'
import { Route as ApiTropesIndexRouteImport } from './routes/api/tropes/index'
import { Route as ApiTemplatesIndexRouteImport } from './routes/api/templates/index'
import { Route as ApiStoriesIndexRouteImport } from './routes/api/stories/index'
import { Route as ApiProfileIndexRouteImport } from './routes/api/profile/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTropesIndexRouteImport } from './routes/admin/tropes/index'
import { Route as AdminTemplatesIndexRouteImport } from './routes/admin/templates/index'
import { Route as AdminAuditLogsIndexRouteImport } from './routes/admin/audit-logs/index'
import { Route as StoryIdReadRouteImport } from './routes/story/$id.read'
import { Route as StoryIdInfoRouteImport } from './routes/story/$id.info'
import { Route as ApiTemplatesIdRouteImport } from './routes/api/templates/$id'
import { Route as ApiStoriesUserRouteImport } from './routes/api/stories/user'
import { Route as ApiStoriesIdRouteImport } from './routes/api/stories/$id'
import { Route as ApiProfilePasswordRouteImport } from './routes/api/profile/password'
import { Route as ApiProfileDataRouteImport } from './routes/api/profile/data'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiAdminDashboardRouteImport } from './routes/api/admin/dashboard'
import { Route as ApiAdminAuditLogsRouteImport } from './routes/api/admin/audit-logs'
import { Route as AdminTemplatesNewRouteImport } from './routes/admin/templates/new'
import { Route as AdminTemplatesBulkImportRouteImport } from './routes/admin/templates/bulk-import'
import { Route as ApiAdminUsersIndexRouteImport } from './routes/api/admin/users/index'
import { Route as ApiAdminTropesIndexRouteImport } from './routes/api/admin/tropes/index'
import { Route as ApiAdminTemplatesIndexRouteImport } from './routes/api/admin/templates/index'
import { Route as ApiStoriesIdSceneRouteImport } from './routes/api/stories/$id.scene'
import { Route as ApiStoriesIdFavoriteRouteImport } from './routes/api/stories/$id/favorite'
import { Route as ApiStoriesIdChooseRouteImport } from './routes/api/stories/$id.choose'
import { Route as ApiStoriesIdBranchRouteImport } from './routes/api/stories/$id.branch'
import { Route as ApiAuthCallbackGoogleRouteImport } from './routes/api/auth/callback.google'
import { Route as ApiAdminUsersStatsRouteImport } from './routes/api/admin/users/stats'
import { Route as ApiAdminUsersIdRouteImport } from './routes/api/admin/users/$id'
import { Route as ApiAdminTropesIdRouteImport } from './routes/api/admin/tropes/$id'
import { Route as ApiAdminTemplatesStatsRouteImport } from './routes/api/admin/templates/stats'
import { Route as ApiAdminTemplatesBulkUpdateRouteImport } from './routes/api/admin/templates/bulk-update'
import { Route as ApiAdminTemplatesBulkImportRouteImport } from './routes/api/admin/templates/bulk-import'
import { Route as ApiAdminTemplatesBulkDeleteRouteImport } from './routes/api/admin/templates/bulk-delete'
import { Route as ApiAdminTemplatesIdRouteImport } from './routes/api/admin/templates/$id'
import { Route as AdminUsersIdEditRouteImport } from './routes/admin/users/$id/edit'
import { Route as AdminTemplatesIdEditRouteImport } from './routes/admin/templates/$id/edit'
import { Route as ApiStoriesIdSceneStreamRouteImport } from './routes/api/stories/$id.scene.stream'
import { Route as ApiAdminTemplatesIdStatusRouteImport } from './routes/api/admin/templates/$id.status'
import { Route as ApiAdminTemplatesIdChoicePointsRouteImport } from './routes/api/admin/templates/$id/choice-points'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateIdRoute = TemplateIdRouteImport.update({
  id: '/template/$id',
  path: '/template/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryCreateRoute = StoryCreateRouteImport.update({
  id: '/story/create',
  path: '/story/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/auth/onboarding',
  path: '/auth/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreferencesRoute = ApiPreferencesRouteImport.update({
  id: '/api/preferences',
  path: '/api/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTropesIndexRoute = ApiTropesIndexRouteImport.update({
  id: '/api/tropes/',
  path: '/api/tropes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesIndexRoute = ApiTemplatesIndexRouteImport.update({
  id: '/api/templates/',
  path: '/api/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesIndexRoute = ApiStoriesIndexRouteImport.update({
  id: '/api/stories/',
  path: '/api/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileIndexRoute = ApiProfileIndexRouteImport.update({
  id: '/api/profile/',
  path: '/api/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTropesIndexRoute = AdminTropesIndexRouteImport.update({
  id: '/admin/tropes/',
  path: '/admin/tropes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplatesIndexRoute = AdminTemplatesIndexRouteImport.update({
  id: '/admin/templates/',
  path: '/admin/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsIndexRoute = AdminAuditLogsIndexRouteImport.update({
  id: '/admin/audit-logs/',
  path: '/admin/audit-logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIdReadRoute = StoryIdReadRouteImport.update({
  id: '/story/$id/read',
  path: '/story/$id/read',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIdInfoRoute = StoryIdInfoRouteImport.update({
  id: '/story/$id/info',
  path: '/story/$id/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesIdRoute = ApiTemplatesIdRouteImport.update({
  id: '/api/templates/$id',
  path: '/api/templates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesUserRoute = ApiStoriesUserRouteImport.update({
  id: '/api/stories/user',
  path: '/api/stories/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesIdRoute = ApiStoriesIdRouteImport.update({
  id: '/api/stories/$id',
  path: '/api/stories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilePasswordRoute = ApiProfilePasswordRouteImport.update({
  id: '/api/profile/password',
  path: '/api/profile/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileDataRoute = ApiProfileDataRouteImport.update({
  id: '/api/profile/data',
  path: '/api/profile/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDashboardRoute = ApiAdminDashboardRouteImport.update({
  id: '/api/admin/dashboard',
  path: '/api/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuditLogsRoute = ApiAdminAuditLogsRouteImport.update({
  id: '/api/admin/audit-logs',
  path: '/api/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplatesNewRoute = AdminTemplatesNewRouteImport.update({
  id: '/admin/templates/new',
  path: '/admin/templates/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplatesBulkImportRoute =
  AdminTemplatesBulkImportRouteImport.update({
    id: '/admin/templates/bulk-import',
    path: '/admin/templates/bulk-import',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminUsersIndexRoute = ApiAdminUsersIndexRouteImport.update({
  id: '/api/admin/users/',
  path: '/api/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTropesIndexRoute = ApiAdminTropesIndexRouteImport.update({
  id: '/api/admin/tropes/',
  path: '/api/admin/tropes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTemplatesIndexRoute = ApiAdminTemplatesIndexRouteImport.update({
  id: '/api/admin/templates/',
  path: '/api/admin/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesIdSceneRoute = ApiStoriesIdSceneRouteImport.update({
  id: '/scene',
  path: '/scene',
  getParentRoute: () => ApiStoriesIdRoute,
} as any)
const ApiStoriesIdFavoriteRoute = ApiStoriesIdFavoriteRouteImport.update({
  id: '/favorite',
  path: '/favorite',
  getParentRoute: () => ApiStoriesIdRoute,
} as any)
const ApiStoriesIdChooseRoute = ApiStoriesIdChooseRouteImport.update({
  id: '/choose',
  path: '/choose',
  getParentRoute: () => ApiStoriesIdRoute,
} as any)
const ApiStoriesIdBranchRoute = ApiStoriesIdBranchRouteImport.update({
  id: '/branch',
  path: '/branch',
  getParentRoute: () => ApiStoriesIdRoute,
} as any)
const ApiAuthCallbackGoogleRoute = ApiAuthCallbackGoogleRouteImport.update({
  id: '/api/auth/callback/google',
  path: '/api/auth/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersStatsRoute = ApiAdminUsersStatsRouteImport.update({
  id: '/api/admin/users/stats',
  path: '/api/admin/users/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersIdRoute = ApiAdminUsersIdRouteImport.update({
  id: '/api/admin/users/$id',
  path: '/api/admin/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTropesIdRoute = ApiAdminTropesIdRouteImport.update({
  id: '/api/admin/tropes/$id',
  path: '/api/admin/tropes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTemplatesStatsRoute = ApiAdminTemplatesStatsRouteImport.update({
  id: '/api/admin/templates/stats',
  path: '/api/admin/templates/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTemplatesBulkUpdateRoute =
  ApiAdminTemplatesBulkUpdateRouteImport.update({
    id: '/api/admin/templates/bulk-update',
    path: '/api/admin/templates/bulk-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminTemplatesBulkImportRoute =
  ApiAdminTemplatesBulkImportRouteImport.update({
    id: '/api/admin/templates/bulk-import',
    path: '/api/admin/templates/bulk-import',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminTemplatesBulkDeleteRoute =
  ApiAdminTemplatesBulkDeleteRouteImport.update({
    id: '/api/admin/templates/bulk-delete',
    path: '/api/admin/templates/bulk-delete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminTemplatesIdRoute = ApiAdminTemplatesIdRouteImport.update({
  id: '/api/admin/templates/$id',
  path: '/api/admin/templates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIdEditRoute = AdminUsersIdEditRouteImport.update({
  id: '/admin/users/$id/edit',
  path: '/admin/users/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplatesIdEditRoute = AdminTemplatesIdEditRouteImport.update({
  id: '/admin/templates/$id/edit',
  path: '/admin/templates/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesIdSceneStreamRoute = ApiStoriesIdSceneStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiStoriesIdSceneRoute,
} as any)
const ApiAdminTemplatesIdStatusRoute =
  ApiAdminTemplatesIdStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => ApiAdminTemplatesIdRoute,
  } as any)
const ApiAdminTemplatesIdChoicePointsRoute =
  ApiAdminTemplatesIdChoicePointsRouteImport.update({
    id: '/choice-points',
    path: '/choice-points',
    getParentRoute: () => ApiAdminTemplatesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/cookies': typeof CookiesRoute
  '/library': typeof LibraryRoute
  '/preferences': typeof PreferencesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/api/preferences': typeof ApiPreferencesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/signup': typeof AuthSignupRoute
  '/story/create': typeof StoryCreateRoute
  '/template/$id': typeof TemplateIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/templates/bulk-import': typeof AdminTemplatesBulkImportRoute
  '/admin/templates/new': typeof AdminTemplatesNewRoute
  '/api/admin/audit-logs': typeof ApiAdminAuditLogsRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/profile/data': typeof ApiProfileDataRoute
  '/api/profile/password': typeof ApiProfilePasswordRoute
  '/api/stories/$id': typeof ApiStoriesIdRouteWithChildren
  '/api/stories/user': typeof ApiStoriesUserRoute
  '/api/templates/$id': typeof ApiTemplatesIdRoute
  '/story/$id/info': typeof StoryIdInfoRoute
  '/story/$id/read': typeof StoryIdReadRoute
  '/admin/audit-logs': typeof AdminAuditLogsIndexRoute
  '/admin/templates': typeof AdminTemplatesIndexRoute
  '/admin/tropes': typeof AdminTropesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/api/profile': typeof ApiProfileIndexRoute
  '/api/stories': typeof ApiStoriesIndexRoute
  '/api/templates': typeof ApiTemplatesIndexRoute
  '/api/tropes': typeof ApiTropesIndexRoute
  '/admin/templates/$id/edit': typeof AdminTemplatesIdEditRoute
  '/admin/users/$id/edit': typeof AdminUsersIdEditRoute
  '/api/admin/templates/$id': typeof ApiAdminTemplatesIdRouteWithChildren
  '/api/admin/templates/bulk-delete': typeof ApiAdminTemplatesBulkDeleteRoute
  '/api/admin/templates/bulk-import': typeof ApiAdminTemplatesBulkImportRoute
  '/api/admin/templates/bulk-update': typeof ApiAdminTemplatesBulkUpdateRoute
  '/api/admin/templates/stats': typeof ApiAdminTemplatesStatsRoute
  '/api/admin/tropes/$id': typeof ApiAdminTropesIdRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/admin/users/stats': typeof ApiAdminUsersStatsRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/stories/$id/branch': typeof ApiStoriesIdBranchRoute
  '/api/stories/$id/choose': typeof ApiStoriesIdChooseRoute
  '/api/stories/$id/favorite': typeof ApiStoriesIdFavoriteRoute
  '/api/stories/$id/scene': typeof ApiStoriesIdSceneRouteWithChildren
  '/api/admin/templates': typeof ApiAdminTemplatesIndexRoute
  '/api/admin/tropes': typeof ApiAdminTropesIndexRoute
  '/api/admin/users': typeof ApiAdminUsersIndexRoute
  '/api/admin/templates/$id/choice-points': typeof ApiAdminTemplatesIdChoicePointsRoute
  '/api/admin/templates/$id/status': typeof ApiAdminTemplatesIdStatusRoute
  '/api/stories/$id/scene/stream': typeof ApiStoriesIdSceneStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/cookies': typeof CookiesRoute
  '/library': typeof LibraryRoute
  '/preferences': typeof PreferencesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/api/preferences': typeof ApiPreferencesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/signup': typeof AuthSignupRoute
  '/story/create': typeof StoryCreateRoute
  '/template/$id': typeof TemplateIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/templates/bulk-import': typeof AdminTemplatesBulkImportRoute
  '/admin/templates/new': typeof AdminTemplatesNewRoute
  '/api/admin/audit-logs': typeof ApiAdminAuditLogsRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/profile/data': typeof ApiProfileDataRoute
  '/api/profile/password': typeof ApiProfilePasswordRoute
  '/api/stories/$id': typeof ApiStoriesIdRouteWithChildren
  '/api/stories/user': typeof ApiStoriesUserRoute
  '/api/templates/$id': typeof ApiTemplatesIdRoute
  '/story/$id/info': typeof StoryIdInfoRoute
  '/story/$id/read': typeof StoryIdReadRoute
  '/admin/audit-logs': typeof AdminAuditLogsIndexRoute
  '/admin/templates': typeof AdminTemplatesIndexRoute
  '/admin/tropes': typeof AdminTropesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/api/profile': typeof ApiProfileIndexRoute
  '/api/stories': typeof ApiStoriesIndexRoute
  '/api/templates': typeof ApiTemplatesIndexRoute
  '/api/tropes': typeof ApiTropesIndexRoute
  '/admin/templates/$id/edit': typeof AdminTemplatesIdEditRoute
  '/admin/users/$id/edit': typeof AdminUsersIdEditRoute
  '/api/admin/templates/$id': typeof ApiAdminTemplatesIdRouteWithChildren
  '/api/admin/templates/bulk-delete': typeof ApiAdminTemplatesBulkDeleteRoute
  '/api/admin/templates/bulk-import': typeof ApiAdminTemplatesBulkImportRoute
  '/api/admin/templates/bulk-update': typeof ApiAdminTemplatesBulkUpdateRoute
  '/api/admin/templates/stats': typeof ApiAdminTemplatesStatsRoute
  '/api/admin/tropes/$id': typeof ApiAdminTropesIdRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/admin/users/stats': typeof ApiAdminUsersStatsRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/stories/$id/branch': typeof ApiStoriesIdBranchRoute
  '/api/stories/$id/choose': typeof ApiStoriesIdChooseRoute
  '/api/stories/$id/favorite': typeof ApiStoriesIdFavoriteRoute
  '/api/stories/$id/scene': typeof ApiStoriesIdSceneRouteWithChildren
  '/api/admin/templates': typeof ApiAdminTemplatesIndexRoute
  '/api/admin/tropes': typeof ApiAdminTropesIndexRoute
  '/api/admin/users': typeof ApiAdminUsersIndexRoute
  '/api/admin/templates/$id/choice-points': typeof ApiAdminTemplatesIdChoicePointsRoute
  '/api/admin/templates/$id/status': typeof ApiAdminTemplatesIdStatusRoute
  '/api/stories/$id/scene/stream': typeof ApiStoriesIdSceneStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/cookies': typeof CookiesRoute
  '/library': typeof LibraryRoute
  '/preferences': typeof PreferencesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/api/preferences': typeof ApiPreferencesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/signup': typeof AuthSignupRoute
  '/story/create': typeof StoryCreateRoute
  '/template/$id': typeof TemplateIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/templates/bulk-import': typeof AdminTemplatesBulkImportRoute
  '/admin/templates/new': typeof AdminTemplatesNewRoute
  '/api/admin/audit-logs': typeof ApiAdminAuditLogsRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/profile/data': typeof ApiProfileDataRoute
  '/api/profile/password': typeof ApiProfilePasswordRoute
  '/api/stories/$id': typeof ApiStoriesIdRouteWithChildren
  '/api/stories/user': typeof ApiStoriesUserRoute
  '/api/templates/$id': typeof ApiTemplatesIdRoute
  '/story/$id/info': typeof StoryIdInfoRoute
  '/story/$id/read': typeof StoryIdReadRoute
  '/admin/audit-logs/': typeof AdminAuditLogsIndexRoute
  '/admin/templates/': typeof AdminTemplatesIndexRoute
  '/admin/tropes/': typeof AdminTropesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/api/profile/': typeof ApiProfileIndexRoute
  '/api/stories/': typeof ApiStoriesIndexRoute
  '/api/templates/': typeof ApiTemplatesIndexRoute
  '/api/tropes/': typeof ApiTropesIndexRoute
  '/admin/templates/$id/edit': typeof AdminTemplatesIdEditRoute
  '/admin/users/$id/edit': typeof AdminUsersIdEditRoute
  '/api/admin/templates/$id': typeof ApiAdminTemplatesIdRouteWithChildren
  '/api/admin/templates/bulk-delete': typeof ApiAdminTemplatesBulkDeleteRoute
  '/api/admin/templates/bulk-import': typeof ApiAdminTemplatesBulkImportRoute
  '/api/admin/templates/bulk-update': typeof ApiAdminTemplatesBulkUpdateRoute
  '/api/admin/templates/stats': typeof ApiAdminTemplatesStatsRoute
  '/api/admin/tropes/$id': typeof ApiAdminTropesIdRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/admin/users/stats': typeof ApiAdminUsersStatsRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/stories/$id/branch': typeof ApiStoriesIdBranchRoute
  '/api/stories/$id/choose': typeof ApiStoriesIdChooseRoute
  '/api/stories/$id/favorite': typeof ApiStoriesIdFavoriteRoute
  '/api/stories/$id/scene': typeof ApiStoriesIdSceneRouteWithChildren
  '/api/admin/templates/': typeof ApiAdminTemplatesIndexRoute
  '/api/admin/tropes/': typeof ApiAdminTropesIndexRoute
  '/api/admin/users/': typeof ApiAdminUsersIndexRoute
  '/api/admin/templates/$id/choice-points': typeof ApiAdminTemplatesIdChoicePointsRoute
  '/api/admin/templates/$id/status': typeof ApiAdminTemplatesIdStatusRoute
  '/api/stories/$id/scene/stream': typeof ApiStoriesIdSceneStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/cookies'
    | '/library'
    | '/preferences'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/api/preferences'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/signup'
    | '/story/create'
    | '/template/$id'
    | '/admin'
    | '/admin/templates/bulk-import'
    | '/admin/templates/new'
    | '/api/admin/audit-logs'
    | '/api/admin/dashboard'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/signup'
    | '/api/profile/data'
    | '/api/profile/password'
    | '/api/stories/$id'
    | '/api/stories/user'
    | '/api/templates/$id'
    | '/story/$id/info'
    | '/story/$id/read'
    | '/admin/audit-logs'
    | '/admin/templates'
    | '/admin/tropes'
    | '/admin/users'
    | '/api/profile'
    | '/api/stories'
    | '/api/templates'
    | '/api/tropes'
    | '/admin/templates/$id/edit'
    | '/admin/users/$id/edit'
    | '/api/admin/templates/$id'
    | '/api/admin/templates/bulk-delete'
    | '/api/admin/templates/bulk-import'
    | '/api/admin/templates/bulk-update'
    | '/api/admin/templates/stats'
    | '/api/admin/tropes/$id'
    | '/api/admin/users/$id'
    | '/api/admin/users/stats'
    | '/api/auth/callback/google'
    | '/api/stories/$id/branch'
    | '/api/stories/$id/choose'
    | '/api/stories/$id/favorite'
    | '/api/stories/$id/scene'
    | '/api/admin/templates'
    | '/api/admin/tropes'
    | '/api/admin/users'
    | '/api/admin/templates/$id/choice-points'
    | '/api/admin/templates/$id/status'
    | '/api/stories/$id/scene/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/cookies'
    | '/library'
    | '/preferences'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/api/preferences'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/signup'
    | '/story/create'
    | '/template/$id'
    | '/admin'
    | '/admin/templates/bulk-import'
    | '/admin/templates/new'
    | '/api/admin/audit-logs'
    | '/api/admin/dashboard'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/signup'
    | '/api/profile/data'
    | '/api/profile/password'
    | '/api/stories/$id'
    | '/api/stories/user'
    | '/api/templates/$id'
    | '/story/$id/info'
    | '/story/$id/read'
    | '/admin/audit-logs'
    | '/admin/templates'
    | '/admin/tropes'
    | '/admin/users'
    | '/api/profile'
    | '/api/stories'
    | '/api/templates'
    | '/api/tropes'
    | '/admin/templates/$id/edit'
    | '/admin/users/$id/edit'
    | '/api/admin/templates/$id'
    | '/api/admin/templates/bulk-delete'
    | '/api/admin/templates/bulk-import'
    | '/api/admin/templates/bulk-update'
    | '/api/admin/templates/stats'
    | '/api/admin/tropes/$id'
    | '/api/admin/users/$id'
    | '/api/admin/users/stats'
    | '/api/auth/callback/google'
    | '/api/stories/$id/branch'
    | '/api/stories/$id/choose'
    | '/api/stories/$id/favorite'
    | '/api/stories/$id/scene'
    | '/api/admin/templates'
    | '/api/admin/tropes'
    | '/api/admin/users'
    | '/api/admin/templates/$id/choice-points'
    | '/api/admin/templates/$id/status'
    | '/api/stories/$id/scene/stream'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/cookies'
    | '/library'
    | '/preferences'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/api/preferences'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/signup'
    | '/story/create'
    | '/template/$id'
    | '/admin/'
    | '/admin/templates/bulk-import'
    | '/admin/templates/new'
    | '/api/admin/audit-logs'
    | '/api/admin/dashboard'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/signup'
    | '/api/profile/data'
    | '/api/profile/password'
    | '/api/stories/$id'
    | '/api/stories/user'
    | '/api/templates/$id'
    | '/story/$id/info'
    | '/story/$id/read'
    | '/admin/audit-logs/'
    | '/admin/templates/'
    | '/admin/tropes/'
    | '/admin/users/'
    | '/api/profile/'
    | '/api/stories/'
    | '/api/templates/'
    | '/api/tropes/'
    | '/admin/templates/$id/edit'
    | '/admin/users/$id/edit'
    | '/api/admin/templates/$id'
    | '/api/admin/templates/bulk-delete'
    | '/api/admin/templates/bulk-import'
    | '/api/admin/templates/bulk-update'
    | '/api/admin/templates/stats'
    | '/api/admin/tropes/$id'
    | '/api/admin/users/$id'
    | '/api/admin/users/stats'
    | '/api/auth/callback/google'
    | '/api/stories/$id/branch'
    | '/api/stories/$id/choose'
    | '/api/stories/$id/favorite'
    | '/api/stories/$id/scene'
    | '/api/admin/templates/'
    | '/api/admin/tropes/'
    | '/api/admin/users/'
    | '/api/admin/templates/$id/choice-points'
    | '/api/admin/templates/$id/status'
    | '/api/stories/$id/scene/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  CookiesRoute: typeof CookiesRoute
  LibraryRoute: typeof LibraryRoute
  PreferencesRoute: typeof PreferencesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  TermsRoute: typeof TermsRoute
  ApiPreferencesRoute: typeof ApiPreferencesRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthSignupRoute: typeof AuthSignupRoute
  StoryCreateRoute: typeof StoryCreateRoute
  TemplateIdRoute: typeof TemplateIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTemplatesBulkImportRoute: typeof AdminTemplatesBulkImportRoute
  AdminTemplatesNewRoute: typeof AdminTemplatesNewRoute
  ApiAdminAuditLogsRoute: typeof ApiAdminAuditLogsRoute
  ApiAdminDashboardRoute: typeof ApiAdminDashboardRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiProfileDataRoute: typeof ApiProfileDataRoute
  ApiProfilePasswordRoute: typeof ApiProfilePasswordRoute
  ApiStoriesIdRoute: typeof ApiStoriesIdRouteWithChildren
  ApiStoriesUserRoute: typeof ApiStoriesUserRoute
  ApiTemplatesIdRoute: typeof ApiTemplatesIdRoute
  StoryIdInfoRoute: typeof StoryIdInfoRoute
  StoryIdReadRoute: typeof StoryIdReadRoute
  AdminAuditLogsIndexRoute: typeof AdminAuditLogsIndexRoute
  AdminTemplatesIndexRoute: typeof AdminTemplatesIndexRoute
  AdminTropesIndexRoute: typeof AdminTropesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  ApiProfileIndexRoute: typeof ApiProfileIndexRoute
  ApiStoriesIndexRoute: typeof ApiStoriesIndexRoute
  ApiTemplatesIndexRoute: typeof ApiTemplatesIndexRoute
  ApiTropesIndexRoute: typeof ApiTropesIndexRoute
  AdminTemplatesIdEditRoute: typeof AdminTemplatesIdEditRoute
  AdminUsersIdEditRoute: typeof AdminUsersIdEditRoute
  ApiAdminTemplatesIdRoute: typeof ApiAdminTemplatesIdRouteWithChildren
  ApiAdminTemplatesBulkDeleteRoute: typeof ApiAdminTemplatesBulkDeleteRoute
  ApiAdminTemplatesBulkImportRoute: typeof ApiAdminTemplatesBulkImportRoute
  ApiAdminTemplatesBulkUpdateRoute: typeof ApiAdminTemplatesBulkUpdateRoute
  ApiAdminTemplatesStatsRoute: typeof ApiAdminTemplatesStatsRoute
  ApiAdminTropesIdRoute: typeof ApiAdminTropesIdRoute
  ApiAdminUsersIdRoute: typeof ApiAdminUsersIdRoute
  ApiAdminUsersStatsRoute: typeof ApiAdminUsersStatsRoute
  ApiAuthCallbackGoogleRoute: typeof ApiAuthCallbackGoogleRoute
  ApiAdminTemplatesIndexRoute: typeof ApiAdminTemplatesIndexRoute
  ApiAdminTropesIndexRoute: typeof ApiAdminTropesIndexRoute
  ApiAdminUsersIndexRoute: typeof ApiAdminUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$id': {
      id: '/template/$id'
      path: '/template/$id'
      fullPath: '/template/$id'
      preLoaderRoute: typeof TemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/create': {
      id: '/story/create'
      path: '/story/create'
      fullPath: '/story/create'
      preLoaderRoute: typeof StoryCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/onboarding': {
      id: '/auth/onboarding'
      path: '/auth/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preferences': {
      id: '/api/preferences'
      path: '/api/preferences'
      fullPath: '/api/preferences'
      preLoaderRoute: typeof ApiPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tropes/': {
      id: '/api/tropes/'
      path: '/api/tropes'
      fullPath: '/api/tropes'
      preLoaderRoute: typeof ApiTropesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates/': {
      id: '/api/templates/'
      path: '/api/templates'
      fullPath: '/api/templates'
      preLoaderRoute: typeof ApiTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories/': {
      id: '/api/stories/'
      path: '/api/stories'
      fullPath: '/api/stories'
      preLoaderRoute: typeof ApiStoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/': {
      id: '/api/profile/'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tropes/': {
      id: '/admin/tropes/'
      path: '/admin/tropes'
      fullPath: '/admin/tropes'
      preLoaderRoute: typeof AdminTropesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/templates/': {
      id: '/admin/templates/'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs/': {
      id: '/admin/audit-logs/'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$id/read': {
      id: '/story/$id/read'
      path: '/story/$id/read'
      fullPath: '/story/$id/read'
      preLoaderRoute: typeof StoryIdReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$id/info': {
      id: '/story/$id/info'
      path: '/story/$id/info'
      fullPath: '/story/$id/info'
      preLoaderRoute: typeof StoryIdInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates/$id': {
      id: '/api/templates/$id'
      path: '/api/templates/$id'
      fullPath: '/api/templates/$id'
      preLoaderRoute: typeof ApiTemplatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories/user': {
      id: '/api/stories/user'
      path: '/api/stories/user'
      fullPath: '/api/stories/user'
      preLoaderRoute: typeof ApiStoriesUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories/$id': {
      id: '/api/stories/$id'
      path: '/api/stories/$id'
      fullPath: '/api/stories/$id'
      preLoaderRoute: typeof ApiStoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/password': {
      id: '/api/profile/password'
      path: '/api/profile/password'
      fullPath: '/api/profile/password'
      preLoaderRoute: typeof ApiProfilePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/data': {
      id: '/api/profile/data'
      path: '/api/profile/data'
      fullPath: '/api/profile/data'
      preLoaderRoute: typeof ApiProfileDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/dashboard': {
      id: '/api/admin/dashboard'
      path: '/api/admin/dashboard'
      fullPath: '/api/admin/dashboard'
      preLoaderRoute: typeof ApiAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/audit-logs': {
      id: '/api/admin/audit-logs'
      path: '/api/admin/audit-logs'
      fullPath: '/api/admin/audit-logs'
      preLoaderRoute: typeof ApiAdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/templates/new': {
      id: '/admin/templates/new'
      path: '/admin/templates/new'
      fullPath: '/admin/templates/new'
      preLoaderRoute: typeof AdminTemplatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/templates/bulk-import': {
      id: '/admin/templates/bulk-import'
      path: '/admin/templates/bulk-import'
      fullPath: '/admin/templates/bulk-import'
      preLoaderRoute: typeof AdminTemplatesBulkImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/': {
      id: '/api/admin/users/'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/tropes/': {
      id: '/api/admin/tropes/'
      path: '/api/admin/tropes'
      fullPath: '/api/admin/tropes'
      preLoaderRoute: typeof ApiAdminTropesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/templates/': {
      id: '/api/admin/templates/'
      path: '/api/admin/templates'
      fullPath: '/api/admin/templates'
      preLoaderRoute: typeof ApiAdminTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories/$id/scene': {
      id: '/api/stories/$id/scene'
      path: '/scene'
      fullPath: '/api/stories/$id/scene'
      preLoaderRoute: typeof ApiStoriesIdSceneRouteImport
      parentRoute: typeof ApiStoriesIdRoute
    }
    '/api/stories/$id/favorite': {
      id: '/api/stories/$id/favorite'
      path: '/favorite'
      fullPath: '/api/stories/$id/favorite'
      preLoaderRoute: typeof ApiStoriesIdFavoriteRouteImport
      parentRoute: typeof ApiStoriesIdRoute
    }
    '/api/stories/$id/choose': {
      id: '/api/stories/$id/choose'
      path: '/choose'
      fullPath: '/api/stories/$id/choose'
      preLoaderRoute: typeof ApiStoriesIdChooseRouteImport
      parentRoute: typeof ApiStoriesIdRoute
    }
    '/api/stories/$id/branch': {
      id: '/api/stories/$id/branch'
      path: '/branch'
      fullPath: '/api/stories/$id/branch'
      preLoaderRoute: typeof ApiStoriesIdBranchRouteImport
      parentRoute: typeof ApiStoriesIdRoute
    }
    '/api/auth/callback/google': {
      id: '/api/auth/callback/google'
      path: '/api/auth/callback/google'
      fullPath: '/api/auth/callback/google'
      preLoaderRoute: typeof ApiAuthCallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/stats': {
      id: '/api/admin/users/stats'
      path: '/api/admin/users/stats'
      fullPath: '/api/admin/users/stats'
      preLoaderRoute: typeof ApiAdminUsersStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/$id': {
      id: '/api/admin/users/$id'
      path: '/api/admin/users/$id'
      fullPath: '/api/admin/users/$id'
      preLoaderRoute: typeof ApiAdminUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/tropes/$id': {
      id: '/api/admin/tropes/$id'
      path: '/api/admin/tropes/$id'
      fullPath: '/api/admin/tropes/$id'
      preLoaderRoute: typeof ApiAdminTropesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/templates/stats': {
      id: '/api/admin/templates/stats'
      path: '/api/admin/templates/stats'
      fullPath: '/api/admin/templates/stats'
      preLoaderRoute: typeof ApiAdminTemplatesStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/templates/bulk-update': {
      id: '/api/admin/templates/bulk-update'
      path: '/api/admin/templates/bulk-update'
      fullPath: '/api/admin/templates/bulk-update'
      preLoaderRoute: typeof ApiAdminTemplatesBulkUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/templates/bulk-import': {
      id: '/api/admin/templates/bulk-import'
      path: '/api/admin/templates/bulk-import'
      fullPath: '/api/admin/templates/bulk-import'
      preLoaderRoute: typeof ApiAdminTemplatesBulkImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/templates/bulk-delete': {
      id: '/api/admin/templates/bulk-delete'
      path: '/api/admin/templates/bulk-delete'
      fullPath: '/api/admin/templates/bulk-delete'
      preLoaderRoute: typeof ApiAdminTemplatesBulkDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/templates/$id': {
      id: '/api/admin/templates/$id'
      path: '/api/admin/templates/$id'
      fullPath: '/api/admin/templates/$id'
      preLoaderRoute: typeof ApiAdminTemplatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$id/edit': {
      id: '/admin/users/$id/edit'
      path: '/admin/users/$id/edit'
      fullPath: '/admin/users/$id/edit'
      preLoaderRoute: typeof AdminUsersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/templates/$id/edit': {
      id: '/admin/templates/$id/edit'
      path: '/admin/templates/$id/edit'
      fullPath: '/admin/templates/$id/edit'
      preLoaderRoute: typeof AdminTemplatesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories/$id/scene/stream': {
      id: '/api/stories/$id/scene/stream'
      path: '/stream'
      fullPath: '/api/stories/$id/scene/stream'
      preLoaderRoute: typeof ApiStoriesIdSceneStreamRouteImport
      parentRoute: typeof ApiStoriesIdSceneRoute
    }
    '/api/admin/templates/$id/status': {
      id: '/api/admin/templates/$id/status'
      path: '/status'
      fullPath: '/api/admin/templates/$id/status'
      preLoaderRoute: typeof ApiAdminTemplatesIdStatusRouteImport
      parentRoute: typeof ApiAdminTemplatesIdRoute
    }
    '/api/admin/templates/$id/choice-points': {
      id: '/api/admin/templates/$id/choice-points'
      path: '/choice-points'
      fullPath: '/api/admin/templates/$id/choice-points'
      preLoaderRoute: typeof ApiAdminTemplatesIdChoicePointsRouteImport
      parentRoute: typeof ApiAdminTemplatesIdRoute
    }
  }
}

interface ApiStoriesIdSceneRouteChildren {
  ApiStoriesIdSceneStreamRoute: typeof ApiStoriesIdSceneStreamRoute
}

const ApiStoriesIdSceneRouteChildren: ApiStoriesIdSceneRouteChildren = {
  ApiStoriesIdSceneStreamRoute: ApiStoriesIdSceneStreamRoute,
}

const ApiStoriesIdSceneRouteWithChildren =
  ApiStoriesIdSceneRoute._addFileChildren(ApiStoriesIdSceneRouteChildren)

interface ApiStoriesIdRouteChildren {
  ApiStoriesIdBranchRoute: typeof ApiStoriesIdBranchRoute
  ApiStoriesIdChooseRoute: typeof ApiStoriesIdChooseRoute
  ApiStoriesIdFavoriteRoute: typeof ApiStoriesIdFavoriteRoute
  ApiStoriesIdSceneRoute: typeof ApiStoriesIdSceneRouteWithChildren
}

const ApiStoriesIdRouteChildren: ApiStoriesIdRouteChildren = {
  ApiStoriesIdBranchRoute: ApiStoriesIdBranchRoute,
  ApiStoriesIdChooseRoute: ApiStoriesIdChooseRoute,
  ApiStoriesIdFavoriteRoute: ApiStoriesIdFavoriteRoute,
  ApiStoriesIdSceneRoute: ApiStoriesIdSceneRouteWithChildren,
}

const ApiStoriesIdRouteWithChildren = ApiStoriesIdRoute._addFileChildren(
  ApiStoriesIdRouteChildren,
)

interface ApiAdminTemplatesIdRouteChildren {
  ApiAdminTemplatesIdChoicePointsRoute: typeof ApiAdminTemplatesIdChoicePointsRoute
  ApiAdminTemplatesIdStatusRoute: typeof ApiAdminTemplatesIdStatusRoute
}

const ApiAdminTemplatesIdRouteChildren: ApiAdminTemplatesIdRouteChildren = {
  ApiAdminTemplatesIdChoicePointsRoute: ApiAdminTemplatesIdChoicePointsRoute,
  ApiAdminTemplatesIdStatusRoute: ApiAdminTemplatesIdStatusRoute,
}

const ApiAdminTemplatesIdRouteWithChildren =
  ApiAdminTemplatesIdRoute._addFileChildren(ApiAdminTemplatesIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  CookiesRoute: CookiesRoute,
  LibraryRoute: LibraryRoute,
  PreferencesRoute: PreferencesRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  TermsRoute: TermsRoute,
  ApiPreferencesRoute: ApiPreferencesRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthSignupRoute: AuthSignupRoute,
  StoryCreateRoute: StoryCreateRoute,
  TemplateIdRoute: TemplateIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTemplatesBulkImportRoute: AdminTemplatesBulkImportRoute,
  AdminTemplatesNewRoute: AdminTemplatesNewRoute,
  ApiAdminAuditLogsRoute: ApiAdminAuditLogsRoute,
  ApiAdminDashboardRoute: ApiAdminDashboardRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiProfileDataRoute: ApiProfileDataRoute,
  ApiProfilePasswordRoute: ApiProfilePasswordRoute,
  ApiStoriesIdRoute: ApiStoriesIdRouteWithChildren,
  ApiStoriesUserRoute: ApiStoriesUserRoute,
  ApiTemplatesIdRoute: ApiTemplatesIdRoute,
  StoryIdInfoRoute: StoryIdInfoRoute,
  StoryIdReadRoute: StoryIdReadRoute,
  AdminAuditLogsIndexRoute: AdminAuditLogsIndexRoute,
  AdminTemplatesIndexRoute: AdminTemplatesIndexRoute,
  AdminTropesIndexRoute: AdminTropesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  ApiProfileIndexRoute: ApiProfileIndexRoute,
  ApiStoriesIndexRoute: ApiStoriesIndexRoute,
  ApiTemplatesIndexRoute: ApiTemplatesIndexRoute,
  ApiTropesIndexRoute: ApiTropesIndexRoute,
  AdminTemplatesIdEditRoute: AdminTemplatesIdEditRoute,
  AdminUsersIdEditRoute: AdminUsersIdEditRoute,
  ApiAdminTemplatesIdRoute: ApiAdminTemplatesIdRouteWithChildren,
  ApiAdminTemplatesBulkDeleteRoute: ApiAdminTemplatesBulkDeleteRoute,
  ApiAdminTemplatesBulkImportRoute: ApiAdminTemplatesBulkImportRoute,
  ApiAdminTemplatesBulkUpdateRoute: ApiAdminTemplatesBulkUpdateRoute,
  ApiAdminTemplatesStatsRoute: ApiAdminTemplatesStatsRoute,
  ApiAdminTropesIdRoute: ApiAdminTropesIdRoute,
  ApiAdminUsersIdRoute: ApiAdminUsersIdRoute,
  ApiAdminUsersStatsRoute: ApiAdminUsersStatsRoute,
  ApiAuthCallbackGoogleRoute: ApiAuthCallbackGoogleRoute,
  ApiAdminTemplatesIndexRoute: ApiAdminTemplatesIndexRoute,
  ApiAdminTropesIndexRoute: ApiAdminTropesIndexRoute,
  ApiAdminUsersIndexRoute: ApiAdminUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
